name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.release.outputs.release_body }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate the full changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff-full
        with:
          config: .cliff.toml
          args: -vv
        env:
          OUTPUT: CHANGELOG.md
      - name: Generate latest changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff-latest
        with:
          config: .cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: LATEST-CHANGES.md
      - name: Set the release body
        id: release
        shell: bash
        run: |
          r=$(cat ${{ steps.git-cliff-latest.outputs.changelog }})
          r="$(printf "$r" | tail -n +3)"
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"
          echo "::set-output name=release_body::$r"
